/* =============================================================
   Sample data for the ASHA portal.

   Used only when no Supabase project is connected. Every record is
   obviously a placeholder and every facility reference is marked
   unverified, so the interface stamps them as unconfirmed rather
   than presenting them as fact.

   Names are ordinary Indian names chosen at random and belong to
   nobody. Phone numbers use the 99999-xxxxx reserved-looking block
   and are not dialable.
   ============================================================= */

const today = () => new Date();
const daysAgo = (n) => {
  const d = today();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};
const dateAgo = (n) => daysAgo(n).slice(0, 10);

export const SAMPLE_ASHA = {
  id: 'demo-asha-0001',
  full_name: 'Demo ASHA worker',
  asha_code: 'DEMO-0001',
  phone: '99999-00001',
  block: 'Demo Block',
  sub_centre: 'Demo Sub-centre',
  district: 'Demo District',
  state: 'Demo State',
  villages: ['Demo Village', 'Chhoti Basti', 'Naya Tola'],
  households: 148,
  supervisor_name: 'Demo ANM',
  supervisor_phone: '99999-00002',
  active: true,
  joined_on: '2021-06-14',
};

export const SAMPLE_ALERTS = [
  {
    id: 'a1',
    citizen_name: 'Sunita Devi',
    citizen_phone: '99999-10001',
    village: 'Demo Village',
    title: 'Bleeding in eighth month of pregnancy',
    body: 'Reported through the emergency button at 06:40. Third pregnancy. Nearest facility with a blood bank is the district hospital, roughly 22 km away.',
    category: 'maternal',
    severity: 'critical',
    status: 'new',
    source: 'emergency_button',
    created_at: daysAgo(0),
    notes: null,
  },
  {
    id: 'a2',
    citizen_name: 'Ramesh Kumar',
    citizen_phone: '99999-10002',
    village: 'Naya Tola',
    title: 'Child, age 3, fever for four days',
    body: 'Asked the voice assistant about fever that will not come down. No convulsions reported. Advised to attend the PHC today.',
    category: 'child',
    severity: 'high',
    status: 'new',
    source: 'assistant',
    created_at: daysAgo(0),
    notes: null,
  },
  {
    id: 'a3',
    citizen_name: 'Lakshmi Bai',
    citizen_phone: '99999-10003',
    village: 'Chhoti Basti',
    title: 'Missed second antenatal check-up',
    body: 'Due for her second ANC eleven days ago. PMSMA clinic runs on the 9th at the PHC.',
    category: 'maternal',
    severity: 'moderate',
    status: 'acknowledged',
    source: 'manual',
    created_at: daysAgo(2),
    acknowledged_at: daysAgo(1),
    notes: 'Spoke to her mother-in-law. Will come on the 9th.',
  },
  {
    id: 'a4',
    citizen_name: 'Anita Sharma',
    citizen_phone: '99999-10004',
    village: 'Demo Village',
    title: 'Asking whether she qualifies for PMMVY',
    body: 'First pregnancy, no bank account in her own name yet. That is the blocker, not eligibility.',
    category: 'schemes',
    severity: 'low',
    status: 'acknowledged',
    source: 'assistant',
    created_at: daysAgo(3),
    acknowledged_at: daysAgo(3),
    notes: null,
  },
  {
    id: 'a5',
    citizen_name: 'Mohan Lal',
    citizen_phone: '99999-10005',
    village: 'Naya Tola',
    title: 'Diabetes medicines finished',
    body: 'Out of metformin for six days. Free supply available at the CHC.',
    category: 'chronic',
    severity: 'moderate',
    status: 'actioned',
    source: 'manual',
    created_at: daysAgo(5),
    acknowledged_at: daysAgo(5),
    notes: 'Collected from the CHC on the same day.',
  },
  {
    id: 'a6',
    citizen_name: 'Farida Begum',
    citizen_phone: '99999-10006',
    village: 'Chhoti Basti',
    title: 'Newborn weight check overdue',
    body: 'Delivered fifteen days ago at the CHC. Weight not recorded since discharge.',
    category: 'child',
    severity: 'moderate',
    status: 'closed',
    source: 'manual',
    created_at: daysAgo(9),
    acknowledged_at: daysAgo(8),
    closed_at: daysAgo(6),
    notes: 'Weighed at home. 2.9 kg, gaining. No action needed.',
  },
];

export const SAMPLE_REFERRALS = [
  {
    id: 'r1',
    patient_name: 'Sunita Devi',
    patient_age: 27,
    patient_gender: 'Female',
    patient_phone: '99999-10001',
    village: 'Demo Village',
    reason: 'Antepartum haemorrhage, eighth month',
    symptoms: 'Bleeding since early morning, giddiness, no abdominal pain',
    urgency: 'critical',
    facility_name: 'Sample District Hospital',
    status: 'referred',
    referred_on: dateAgo(0),
    visited_on: null,
    outcome: null,
    notes: 'Sent by 108 ambulance at 07:15. Husband travelling with her.',
    created_at: daysAgo(0),
  },
  {
    id: 'r2',
    patient_name: 'Ramesh Kumar (son, age 3)',
    patient_age: 3,
    patient_gender: 'Male',
    patient_phone: '99999-10002',
    village: 'Naya Tola',
    reason: 'Fever four days, not settling with paracetamol',
    symptoms: 'Fever, poor appetite, no rash, no convulsions',
    urgency: 'high',
    facility_name: 'Sample Primary Health Centre',
    status: 'contacted',
    referred_on: dateAgo(0),
    visited_on: null,
    outcome: null,
    notes: 'PHC informed by phone. Father taking him at 11:00.',
    created_at: daysAgo(0),
  },
  {
    id: 'r3',
    patient_name: 'Lakshmi Bai',
    patient_age: 24,
    patient_gender: 'Female',
    patient_phone: '99999-10003',
    village: 'Chhoti Basti',
    reason: 'Second antenatal check-up, overdue',
    symptoms: 'No complaints. Routine.',
    urgency: 'moderate',
    facility_name: 'Sample Primary Health Centre',
    status: 'acknowledged',
    referred_on: dateAgo(2),
    visited_on: null,
    outcome: null,
    notes: 'Booked for the PMSMA clinic on the 9th.',
    created_at: daysAgo(2),
  },
  {
    id: 'r4',
    patient_name: 'Mohan Lal',
    patient_age: 58,
    patient_gender: 'Male',
    patient_phone: '99999-10005',
    village: 'Naya Tola',
    reason: 'Diabetes medicine refill and sugar check',
    symptoms: 'Out of metformin six days',
    urgency: 'moderate',
    facility_name: 'Sample Community Health Centre',
    status: 'resolved',
    referred_on: dateAgo(5),
    visited_on: dateAgo(5),
    outcome: 'Three months of metformin issued. Fasting sugar 148 mg/dL. Review in one month.',
    notes: null,
    created_at: daysAgo(5),
  },
  {
    id: 'r5',
    patient_name: 'Farida Begum',
    patient_age: 22,
    patient_gender: 'Female',
    patient_phone: '99999-10006',
    village: 'Chhoti Basti',
    reason: 'Postnatal review and newborn weight',
    symptoms: 'Mother well. Baby feeding.',
    urgency: 'low',
    facility_name: 'Sample Primary Health Centre',
    status: 'resolved',
    referred_on: dateAgo(9),
    visited_on: dateAgo(7),
    outcome: 'Both well. Baby 2.9 kg and gaining. Immunisation up to date.',
    notes: null,
    created_at: daysAgo(9),
  },
  {
    id: 'r6',
    patient_name: 'Kailash Yadav',
    patient_age: 41,
    patient_gender: 'Male',
    patient_phone: '99999-10007',
    village: 'Demo Village',
    reason: 'Persistent cough, three weeks — sputum test advised',
    symptoms: 'Cough three weeks, evening fever, weight loss',
    urgency: 'high',
    facility_name: 'Sample Community Health Centre',
    status: 'in_progress',
    referred_on: dateAgo(4),
    visited_on: dateAgo(3),
    outcome: null,
    notes: 'Sputum sent. Result expected this week.',
    created_at: daysAgo(4),
  },
  {
    id: 'r7',
    patient_name: 'Geeta Kumari',
    patient_age: 31,
    patient_gender: 'Female',
    patient_phone: '99999-10008',
    village: 'Naya Tola',
    reason: 'Anaemia, haemoglobin 8.1',
    symptoms: 'Tiredness, breathlessness on climbing',
    urgency: 'moderate',
    facility_name: 'Sample Primary Health Centre',
    status: 'pending',
    referred_on: dateAgo(1),
    visited_on: null,
    outcome: null,
    notes: null,
    created_at: daysAgo(1),
  },
  {
    id: 'r8',
    patient_name: 'Shanti Devi',
    patient_age: 63,
    patient_gender: 'Female',
    patient_phone: '99999-10009',
    village: 'Chhoti Basti',
    reason: 'Cataract screening',
    symptoms: 'Blurred vision, both eyes',
    urgency: 'low',
    facility_name: 'Sample District Hospital',
    status: 'cancelled',
    referred_on: dateAgo(12),
    visited_on: null,
    outcome: null,
    notes: 'Family declined for now. Will reconsider after the harvest.',
    created_at: daysAgo(12),
  },
];

export const SAMPLE_FACILITIES = [
  {
    id: 'f1',
    name: 'Sample Primary Health Centre',
    kind: 'phc',
    address: 'Placeholder address — replace with registry data',
    village: 'Demo Village',
    block: 'Demo Block',
    district: 'Demo District',
    phone: null,
    open_24x7: false,
    has_ambulance: false,
    services: ['Outpatient care', 'Antenatal check-up', 'Immunisation', 'Basic laboratory'],
    verification: 'unverified',
    source: 'DEMO PLACEHOLDER — not a real facility',
    distance_km: 3.2,
  },
  {
    id: 'f2',
    name: 'Sample Community Health Centre',
    kind: 'chc',
    address: 'Placeholder address — replace with registry data',
    village: 'Demo Town',
    block: 'Demo Block',
    district: 'Demo District',
    phone: null,
    open_24x7: true,
    has_ambulance: true,
    services: ['Inpatient beds', 'Emergency care', 'Institutional delivery', 'X-ray', 'Laboratory'],
    verification: 'unverified',
    source: 'DEMO PLACEHOLDER — not a real facility',
    distance_km: 11.6,
  },
  {
    id: 'f3',
    name: 'Sample District Hospital',
    kind: 'district_hospital',
    address: 'Placeholder address — replace with registry data',
    village: 'Demo City',
    block: 'Demo Block',
    district: 'Demo District',
    phone: null,
    open_24x7: true,
    has_ambulance: true,
    services: [
      'Emergency and trauma',
      'Caesarean section',
      'Blood bank',
      'Specialist outpatient',
      'Intensive care',
    ],
    verification: 'unverified',
    source: 'DEMO PLACEHOLDER — not a real facility',
    distance_km: 22.4,
  },
];

/* Deliberately empty. A camp that does not exist sends someone
   walking to a field for nothing, so the app says so instead. */
export const SAMPLE_CAMPS = [];
